### ISSUE TITLE
Add social icon(s) to top navbar

### ISSUE THREAD

**Issue by noahsbwilliams** [optoutnews/Edition#1]
- [x] Instagram

**Comment by noahsbwilliams** [comment]
@devrmateo another one that may be low-hanging fruit if you're interested. Ghost has integrated fields for the Twitter and Instagram fields, but adding an Instagram icon will require finding a suitable icon file and just hardcoding in https://instagram.com/optoutapp

**Comment by devrmateo** [comment]
@noahsbwilliams, I went ahead and took care of this one, too. Everything seems to be good. Check it out and let me know what you think

**Comment by noahsbwilliams** [comment]
It looks great, Matthew!
