### ISSUE TITLE
Image size issue

### ISSUE THREAD

**Issue by alexkotch** [optoutnews/Edition#11]
In the editor, Ghost began saying that normally-sized images (I've tried 1.3MB to 2MB) are too large for the server.
![Screen Shot 2021-10-13 at 12 48 00 PM](https://user-images.githubusercontent.com/67507257/137198414-b4f065bf-5f4f-4e03-a9eb-4a5285c7bf2a.png)

**Comment by noahsbwilliams** [comment]
Closed as duplicate
