### ISSUE TITLE
Install Google Tag Manager code

### ISSUE THREAD

**Issue by alexkotch** [optoutnews/Edition#73]
We need this installed on all pages of the sites as well as Google Analytics code, which is already installed.

Directions: https://developers.google.com/tag-platform/tag-manager/web

**Comment by devrmateo** [comment]
Yeah, I took care of this last week

**Comment by devrmateo** [comment]
Only for the landing site though. I was waiting for feedback from Sean as to whether I had done it correctly before I went ahead and did the originals site as well

**Comment by alexkotch** [comment]
Ah. i think you must have done it right, so can you do this for originals too now?

**Comment by devrmateo** [comment]
👍
